In [2]:
import torch

def get_jacobian(net, x, noutputs):
    x = x.squeeze()
    n = x.size()[0]
    x = x.repeat(noutputs, 1)
    x.requires_grad_(True)
    y = net(x)
    return torch.autograd.grad(y, x, torch.eye(noutputs))[0]
#     return x.grad.data
x = torch.randn(3).requires_grad_(True)
net = torch.nn.Linear(3,4)
y = net(x)
# y_repeated = net(x_repeated)
grad_inp_repeated = torch.Tensor([1,0,0,0])
print (get_jacobian(net, x, 4))
print (torch.autograd.grad(y, x, grad_inp_repeated)) # get the first row of jacobian matrix

tensor([[ 0.2364,  0.3401,  0.2660],
        [-0.4622,  0.4457, -0.3061],
        [-0.0482,  0.3440, -0.4859],
        [ 0.5764, -0.0361, -0.0525]])
(tensor([0.2364, 0.3401, 0.2660]),)


In [25]:
# jacobian(x,y)
torch.autograd.grad(y,x, torch.Tensor([[1,0,0,0]]))

(tensor([[-0.2356, -0.7961, -0.2054]]),)